name: Release

on:
  push:
    tags:
      - 'v*'
  # 手动触发
  # 允许手动从 Actions tab 运行这个 workflows
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'pnpm'

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: PNPM build
        run: pnpm build

      - name: PNPM test
        run: pnpm test

      - name: Publish to NPM
        run: pnpm --filter=./packages/** publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
